// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "common/auth_method.proto" (package "tempest.common", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum tempest.common.AuthMethod
 */
export enum AuthMethod {
	/**
	 * @generated from protobuf enum value: AUTH_METHOD_UNSPECIFIED = 0;
	 */
	UNSPECIFIED = 0,
	/**
	 * @generated from protobuf enum value: AUTH_METHOD_PLAIN = 1;
	 */
	PLAIN = 1,
	/**
	 * @generated from protobuf enum value: AUTH_METHOD_TICKET = 2;
	 */
	TICKET = 2,
}
