// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "common/country.proto" (package "tempest.common", syntax proto3)
// tslint:disable
/**
 * An enum representing ISO 3166-1 alpha-2 country codes.
 *
 * @generated from protobuf enum tempest.common.CountryCode
 */
export enum CountryCode {
	/**
	 * Default unspecified value.
	 *
	 * @generated from protobuf enum value: COUNTRY_CODE_UNSPECIFIED = 0;
	 */
	COUNTRY_CODE_UNSPECIFIED = 0,
	/**
	 * Afghanistan
	 *
	 * @generated from protobuf enum value: AF = 4;
	 */
	AF = 4,
	/**
	 * Albania
	 *
	 * @generated from protobuf enum value: AL = 8;
	 */
	AL = 8,
	/**
	 * Algeria
	 *
	 * @generated from protobuf enum value: DZ = 12;
	 */
	DZ = 12,
	/**
	 * American Samoa
	 *
	 * @generated from protobuf enum value: AS = 16;
	 */
	AS = 16,
	/**
	 * Andorra
	 *
	 * @generated from protobuf enum value: AD = 20;
	 */
	AD = 20,
	/**
	 * Angola
	 *
	 * @generated from protobuf enum value: AO = 24;
	 */
	AO = 24,
	/**
	 * Anguilla
	 *
	 * @generated from protobuf enum value: AI = 660;
	 */
	AI = 660,
	/**
	 * Antarctica
	 *
	 * @generated from protobuf enum value: AQ = 10;
	 */
	AQ = 10,
	/**
	 * Antigua and Barbuda
	 *
	 * @generated from protobuf enum value: AG = 28;
	 */
	AG = 28,
	/**
	 * Argentina
	 *
	 * @generated from protobuf enum value: AR = 32;
	 */
	AR = 32,
	/**
	 * Armenia
	 *
	 * @generated from protobuf enum value: AM = 51;
	 */
	AM = 51,
	/**
	 * Aruba
	 *
	 * @generated from protobuf enum value: AW = 533;
	 */
	AW = 533,
	/**
	 * Australia
	 *
	 * @generated from protobuf enum value: AU = 36;
	 */
	AU = 36,
	/**
	 * Austria
	 *
	 * @generated from protobuf enum value: AT = 40;
	 */
	AT = 40,
	/**
	 * Azerbaijan
	 *
	 * @generated from protobuf enum value: AZ = 31;
	 */
	AZ = 31,
	/**
	 * Bahamas
	 *
	 * @generated from protobuf enum value: BS = 44;
	 */
	BS = 44,
	/**
	 * Bahrain
	 *
	 * @generated from protobuf enum value: BH = 48;
	 */
	BH = 48,
	/**
	 * Bangladesh
	 *
	 * @generated from protobuf enum value: BD = 50;
	 */
	BD = 50,
	/**
	 * Barbados
	 *
	 * @generated from protobuf enum value: BB = 52;
	 */
	BB = 52,
	/**
	 * Belarus
	 *
	 * @generated from protobuf enum value: BY = 112;
	 */
	BY = 112,
	/**
	 * Belgium
	 *
	 * @generated from protobuf enum value: BE = 56;
	 */
	BE = 56,
	/**
	 * Belize
	 *
	 * @generated from protobuf enum value: BZ = 84;
	 */
	BZ = 84,
	/**
	 * Benin
	 *
	 * @generated from protobuf enum value: BJ = 204;
	 */
	BJ = 204,
	/**
	 * Bermuda
	 *
	 * @generated from protobuf enum value: BM = 60;
	 */
	BM = 60,
	/**
	 * Bhutan
	 *
	 * @generated from protobuf enum value: BT = 64;
	 */
	BT = 64,
	/**
	 * "Bolivia, Plurinational State of"
	 *
	 * @generated from protobuf enum value: BO = 68;
	 */
	BO = 68,
	/**
	 * "Bonaire, Sint Eustatius and Saba"
	 *
	 * @generated from protobuf enum value: BQ = 535;
	 */
	BQ = 535,
	/**
	 * Bosnia and Herzegovina
	 *
	 * @generated from protobuf enum value: BA = 70;
	 */
	BA = 70,
	/**
	 * Botswana
	 *
	 * @generated from protobuf enum value: BW = 72;
	 */
	BW = 72,
	/**
	 * Bouvet Island
	 *
	 * @generated from protobuf enum value: BV = 74;
	 */
	BV = 74,
	/**
	 * Brazil
	 *
	 * @generated from protobuf enum value: BR = 76;
	 */
	BR = 76,
	/**
	 * British Indian Ocean Territory
	 *
	 * @generated from protobuf enum value: IO = 86;
	 */
	IO = 86,
	/**
	 * Brunei Darussalam
	 *
	 * @generated from protobuf enum value: BN = 96;
	 */
	BN = 96,
	/**
	 * Bulgaria
	 *
	 * @generated from protobuf enum value: BG = 100;
	 */
	BG = 100,
	/**
	 * Burkina Faso
	 *
	 * @generated from protobuf enum value: BF = 854;
	 */
	BF = 854,
	/**
	 * Burundi
	 *
	 * @generated from protobuf enum value: BI = 108;
	 */
	BI = 108,
	/**
	 * Cambodia
	 *
	 * @generated from protobuf enum value: KH = 116;
	 */
	KH = 116,
	/**
	 * Cameroon
	 *
	 * @generated from protobuf enum value: CM = 120;
	 */
	CM = 120,
	/**
	 * Canada
	 *
	 * @generated from protobuf enum value: CA = 124;
	 */
	CA = 124,
	/**
	 * Cape Verde
	 *
	 * @generated from protobuf enum value: CV = 132;
	 */
	CV = 132,
	/**
	 * Cayman Islands
	 *
	 * @generated from protobuf enum value: KY = 136;
	 */
	KY = 136,
	/**
	 * Central African Republic
	 *
	 * @generated from protobuf enum value: CF = 140;
	 */
	CF = 140,
	/**
	 * Chad
	 *
	 * @generated from protobuf enum value: TD = 148;
	 */
	TD = 148,
	/**
	 * Chile
	 *
	 * @generated from protobuf enum value: CL = 152;
	 */
	CL = 152,
	/**
	 * China
	 *
	 * @generated from protobuf enum value: CN = 156;
	 */
	CN = 156,
	/**
	 * Christmas Island
	 *
	 * @generated from protobuf enum value: CX = 162;
	 */
	CX = 162,
	/**
	 * Cocos (Keeling) Islands
	 *
	 * @generated from protobuf enum value: CC = 166;
	 */
	CC = 166,
	/**
	 * Colombia
	 *
	 * @generated from protobuf enum value: CO = 170;
	 */
	CO = 170,
	/**
	 * Comoros
	 *
	 * @generated from protobuf enum value: KM = 174;
	 */
	KM = 174,
	/**
	 * Congo
	 *
	 * @generated from protobuf enum value: CG = 178;
	 */
	CG = 178,
	/**
	 * "Congo, the Democratic Republic of the"
	 *
	 * @generated from protobuf enum value: CD = 180;
	 */
	CD = 180,
	/**
	 * Cook Islands
	 *
	 * @generated from protobuf enum value: CK = 184;
	 */
	CK = 184,
	/**
	 * Costa Rica
	 *
	 * @generated from protobuf enum value: CR = 188;
	 */
	CR = 188,
	/**
	 * "Côte d'Ivoire"
	 *
	 * @generated from protobuf enum value: CI = 384;
	 */
	CI = 384,
	/**
	 * Croatia
	 *
	 * @generated from protobuf enum value: HR = 191;
	 */
	HR = 191,
	/**
	 * Cuba
	 *
	 * @generated from protobuf enum value: CU = 192;
	 */
	CU = 192,
	/**
	 * Curaçao
	 *
	 * @generated from protobuf enum value: CW = 531;
	 */
	CW = 531,
	/**
	 * Cyprus
	 *
	 * @generated from protobuf enum value: CY = 196;
	 */
	CY = 196,
	/**
	 * Czech Republic
	 *
	 * @generated from protobuf enum value: CZ = 203;
	 */
	CZ = 203,
	/**
	 * Denmark
	 *
	 * @generated from protobuf enum value: DK = 208;
	 */
	DK = 208,
	/**
	 * Djibouti
	 *
	 * @generated from protobuf enum value: DJ = 262;
	 */
	DJ = 262,
	/**
	 * Dominica
	 *
	 * @generated from protobuf enum value: DM = 212;
	 */
	DM = 212,
	/**
	 * Dominican Republic
	 *
	 * @generated from protobuf enum value: DO = 214;
	 */
	DO = 214,
	/**
	 * Ecuador
	 *
	 * @generated from protobuf enum value: EC = 218;
	 */
	EC = 218,
	/**
	 * Egypt
	 *
	 * @generated from protobuf enum value: EG = 818;
	 */
	EG = 818,
	/**
	 * El Salvador
	 *
	 * @generated from protobuf enum value: SV = 222;
	 */
	SV = 222,
	/**
	 * Equatorial Guinea
	 *
	 * @generated from protobuf enum value: GQ = 226;
	 */
	GQ = 226,
	/**
	 * Eritrea
	 *
	 * @generated from protobuf enum value: ER = 232;
	 */
	ER = 232,
	/**
	 * Estonia
	 *
	 * @generated from protobuf enum value: EE = 233;
	 */
	EE = 233,
	/**
	 * Ethiopia
	 *
	 * @generated from protobuf enum value: ET = 231;
	 */
	ET = 231,
	/**
	 * Falkland Islands (Malvinas)
	 *
	 * @generated from protobuf enum value: FK = 238;
	 */
	FK = 238,
	/**
	 * Faroe Islands
	 *
	 * @generated from protobuf enum value: FO = 234;
	 */
	FO = 234,
	/**
	 * Fiji
	 *
	 * @generated from protobuf enum value: FJ = 242;
	 */
	FJ = 242,
	/**
	 * Finland
	 *
	 * @generated from protobuf enum value: FI = 246;
	 */
	FI = 246,
	/**
	 * France
	 *
	 * @generated from protobuf enum value: FR = 250;
	 */
	FR = 250,
	/**
	 * French Guiana
	 *
	 * @generated from protobuf enum value: GF = 254;
	 */
	GF = 254,
	/**
	 * French Polynesia
	 *
	 * @generated from protobuf enum value: PF = 258;
	 */
	PF = 258,
	/**
	 * French Southern Territories
	 *
	 * @generated from protobuf enum value: TF = 260;
	 */
	TF = 260,
	/**
	 * Gabon
	 *
	 * @generated from protobuf enum value: GA = 266;
	 */
	GA = 266,
	/**
	 * Gambia
	 *
	 * @generated from protobuf enum value: GM = 270;
	 */
	GM = 270,
	/**
	 * Georgia
	 *
	 * @generated from protobuf enum value: GE = 268;
	 */
	GE = 268,
	/**
	 * Germany
	 *
	 * @generated from protobuf enum value: DE = 276;
	 */
	DE = 276,
	/**
	 * Ghana
	 *
	 * @generated from protobuf enum value: GH = 288;
	 */
	GH = 288,
	/**
	 * Gibraltar
	 *
	 * @generated from protobuf enum value: GI = 292;
	 */
	GI = 292,
	/**
	 * Greece
	 *
	 * @generated from protobuf enum value: GR = 300;
	 */
	GR = 300,
	/**
	 * Greenland
	 *
	 * @generated from protobuf enum value: GL = 304;
	 */
	GL = 304,
	/**
	 * Grenada
	 *
	 * @generated from protobuf enum value: GD = 308;
	 */
	GD = 308,
	/**
	 * Guadeloupe
	 *
	 * @generated from protobuf enum value: GP = 312;
	 */
	GP = 312,
	/**
	 * Guam
	 *
	 * @generated from protobuf enum value: GU = 316;
	 */
	GU = 316,
	/**
	 * Guatemala
	 *
	 * @generated from protobuf enum value: GT = 320;
	 */
	GT = 320,
	/**
	 * Guernsey
	 *
	 * @generated from protobuf enum value: GG = 831;
	 */
	GG = 831,
	/**
	 * Guinea
	 *
	 * @generated from protobuf enum value: GN = 324;
	 */
	GN = 324,
	/**
	 * Guinea-Bissau
	 *
	 * @generated from protobuf enum value: GW = 624;
	 */
	GW = 624,
	/**
	 * Guyana
	 *
	 * @generated from protobuf enum value: GY = 328;
	 */
	GY = 328,
	/**
	 * Haiti
	 *
	 * @generated from protobuf enum value: HT = 332;
	 */
	HT = 332,
	/**
	 * Heard Island and McDonald Islands
	 *
	 * @generated from protobuf enum value: HM = 334;
	 */
	HM = 334,
	/**
	 * Holy See (Vatican City State)
	 *
	 * @generated from protobuf enum value: VA = 336;
	 */
	VA = 336,
	/**
	 * Honduras
	 *
	 * @generated from protobuf enum value: HN = 340;
	 */
	HN = 340,
	/**
	 * Hong Kong
	 *
	 * @generated from protobuf enum value: HK = 344;
	 */
	HK = 344,
	/**
	 * Hungary
	 *
	 * @generated from protobuf enum value: HU = 348;
	 */
	HU = 348,
	/**
	 * Iceland
	 *
	 * @generated from protobuf enum value: IS = 352;
	 */
	IS = 352,
	/**
	 * India
	 *
	 * @generated from protobuf enum value: IN = 356;
	 */
	IN = 356,
	/**
	 * Indonesia
	 *
	 * @generated from protobuf enum value: ID = 360;
	 */
	ID = 360,
	/**
	 * "Iran, Islamic Republic of"
	 *
	 * @generated from protobuf enum value: IR = 364;
	 */
	IR = 364,
	/**
	 * Iraq
	 *
	 * @generated from protobuf enum value: IQ = 368;
	 */
	IQ = 368,
	/**
	 * Ireland
	 *
	 * @generated from protobuf enum value: IE = 372;
	 */
	IE = 372,
	/**
	 * Isle of Man
	 *
	 * @generated from protobuf enum value: IM = 833;
	 */
	IM = 833,
	/**
	 * IL = 376; // Israel
	 *
	 * Italy
	 *
	 * @generated from protobuf enum value: IT = 380;
	 */
	IT = 380,
	/**
	 * Jamaica
	 *
	 * @generated from protobuf enum value: JM = 388;
	 */
	JM = 388,
	/**
	 * Japan
	 *
	 * @generated from protobuf enum value: JP = 392;
	 */
	JP = 392,
	/**
	 * Jersey
	 *
	 * @generated from protobuf enum value: JE = 832;
	 */
	JE = 832,
	/**
	 * Jordan
	 *
	 * @generated from protobuf enum value: JO = 400;
	 */
	JO = 400,
	/**
	 * Kazakhstan
	 *
	 * @generated from protobuf enum value: KZ = 398;
	 */
	KZ = 398,
	/**
	 * Kenya
	 *
	 * @generated from protobuf enum value: KE = 404;
	 */
	KE = 404,
	/**
	 * Kiribati
	 *
	 * @generated from protobuf enum value: KI = 296;
	 */
	KI = 296,
	/**
	 * "Korea, Democratic People's Republic of"
	 *
	 * @generated from protobuf enum value: KP = 408;
	 */
	KP = 408,
	/**
	 * "Korea, Republic of"
	 *
	 * @generated from protobuf enum value: KR = 410;
	 */
	KR = 410,
	/**
	 * Kuwait
	 *
	 * @generated from protobuf enum value: KW = 414;
	 */
	KW = 414,
	/**
	 * Kyrgyzstan
	 *
	 * @generated from protobuf enum value: KG = 417;
	 */
	KG = 417,
	/**
	 * Lao People's Democratic Republic
	 *
	 * @generated from protobuf enum value: LA = 418;
	 */
	LA = 418,
	/**
	 * Latvia
	 *
	 * @generated from protobuf enum value: LV = 428;
	 */
	LV = 428,
	/**
	 * Lebanon
	 *
	 * @generated from protobuf enum value: LB = 422;
	 */
	LB = 422,
	/**
	 * Lesotho
	 *
	 * @generated from protobuf enum value: LS = 426;
	 */
	LS = 426,
	/**
	 * Liberia
	 *
	 * @generated from protobuf enum value: LR = 430;
	 */
	LR = 430,
	/**
	 * Libya
	 *
	 * @generated from protobuf enum value: LY = 434;
	 */
	LY = 434,
	/**
	 * Liechtenstein
	 *
	 * @generated from protobuf enum value: LI = 438;
	 */
	LI = 438,
	/**
	 * Lithuania
	 *
	 * @generated from protobuf enum value: LT = 440;
	 */
	LT = 440,
	/**
	 * Luxembourg
	 *
	 * @generated from protobuf enum value: LU = 442;
	 */
	LU = 442,
	/**
	 * Macao
	 *
	 * @generated from protobuf enum value: MO = 446;
	 */
	MO = 446,
	/**
	 * "Macedonia, the former Yugoslav Republic of"
	 *
	 * @generated from protobuf enum value: MK = 807;
	 */
	MK = 807,
	/**
	 * Madagascar
	 *
	 * @generated from protobuf enum value: MG = 450;
	 */
	MG = 450,
	/**
	 * Malawi
	 *
	 * @generated from protobuf enum value: MW = 454;
	 */
	MW = 454,
	/**
	 * Malaysia
	 *
	 * @generated from protobuf enum value: MY = 458;
	 */
	MY = 458,
	/**
	 * Maldives
	 *
	 * @generated from protobuf enum value: MV = 462;
	 */
	MV = 462,
	/**
	 * Mali
	 *
	 * @generated from protobuf enum value: ML = 466;
	 */
	ML = 466,
	/**
	 * Malta
	 *
	 * @generated from protobuf enum value: MT = 470;
	 */
	MT = 470,
	/**
	 * Marshall Islands
	 *
	 * @generated from protobuf enum value: MH = 584;
	 */
	MH = 584,
	/**
	 * Martinique
	 *
	 * @generated from protobuf enum value: MQ = 474;
	 */
	MQ = 474,
	/**
	 * Mauritania
	 *
	 * @generated from protobuf enum value: MR = 478;
	 */
	MR = 478,
	/**
	 * Mauritius
	 *
	 * @generated from protobuf enum value: MU = 480;
	 */
	MU = 480,
	/**
	 * Mayotte
	 *
	 * @generated from protobuf enum value: YT = 175;
	 */
	YT = 175,
	/**
	 * Mexico
	 *
	 * @generated from protobuf enum value: MX = 484;
	 */
	MX = 484,
	/**
	 * "Micronesia, Federated States of"
	 *
	 * @generated from protobuf enum value: FM = 583;
	 */
	FM = 583,
	/**
	 * "Moldova, Republic of"
	 *
	 * @generated from protobuf enum value: MD = 498;
	 */
	MD = 498,
	/**
	 * Monaco
	 *
	 * @generated from protobuf enum value: MC = 492;
	 */
	MC = 492,
	/**
	 * Mongolia
	 *
	 * @generated from protobuf enum value: MN = 496;
	 */
	MN = 496,
	/**
	 * Montenegro
	 *
	 * @generated from protobuf enum value: ME = 499;
	 */
	ME = 499,
	/**
	 * Montserrat
	 *
	 * @generated from protobuf enum value: MS = 500;
	 */
	MS = 500,
	/**
	 * Morocco
	 *
	 * @generated from protobuf enum value: MA = 504;
	 */
	MA = 504,
	/**
	 * Mozambique
	 *
	 * @generated from protobuf enum value: MZ = 508;
	 */
	MZ = 508,
	/**
	 * Myanmar
	 *
	 * @generated from protobuf enum value: MM = 104;
	 */
	MM = 104,
	/**
	 * Namibia
	 *
	 * @generated from protobuf enum value: NA = 516;
	 */
	NA = 516,
	/**
	 * Nauru
	 *
	 * @generated from protobuf enum value: NR = 520;
	 */
	NR = 520,
	/**
	 * Nepal
	 *
	 * @generated from protobuf enum value: NP = 524;
	 */
	NP = 524,
	/**
	 * Netherlands
	 *
	 * @generated from protobuf enum value: NL = 528;
	 */
	NL = 528,
	/**
	 * New Caledonia
	 *
	 * @generated from protobuf enum value: NC = 540;
	 */
	NC = 540,
	/**
	 * New Zealand
	 *
	 * @generated from protobuf enum value: NZ = 554;
	 */
	NZ = 554,
	/**
	 * Nicaragua
	 *
	 * @generated from protobuf enum value: NI = 558;
	 */
	NI = 558,
	/**
	 * Niger
	 *
	 * @generated from protobuf enum value: NE = 562;
	 */
	NE = 562,
	/**
	 * Nigeria
	 *
	 * @generated from protobuf enum value: NG = 566;
	 */
	NG = 566,
	/**
	 * Niue
	 *
	 * @generated from protobuf enum value: NU = 570;
	 */
	NU = 570,
	/**
	 * Norfolk Island
	 *
	 * @generated from protobuf enum value: NF = 574;
	 */
	NF = 574,
	/**
	 * Northern Mariana Islands
	 *
	 * @generated from protobuf enum value: MP = 580;
	 */
	MP = 580,
	/**
	 * Norway
	 *
	 * @generated from protobuf enum value: NO = 578;
	 */
	NO = 578,
	/**
	 * Oman
	 *
	 * @generated from protobuf enum value: OM = 512;
	 */
	OM = 512,
	/**
	 * Pakistan
	 *
	 * @generated from protobuf enum value: PK = 586;
	 */
	PK = 586,
	/**
	 * Palau
	 *
	 * @generated from protobuf enum value: PW = 585;
	 */
	PW = 585,
	/**
	 * Palestine
	 *
	 * @generated from protobuf enum value: PS = 275;
	 */
	PS = 275,
	/**
	 * Panama
	 *
	 * @generated from protobuf enum value: PA = 591;
	 */
	PA = 591,
	/**
	 * Papua New Guinea
	 *
	 * @generated from protobuf enum value: PG = 598;
	 */
	PG = 598,
	/**
	 * Paraguay
	 *
	 * @generated from protobuf enum value: PY = 600;
	 */
	PY = 600,
	/**
	 * Peru
	 *
	 * @generated from protobuf enum value: PE = 604;
	 */
	PE = 604,
	/**
	 * Philippines
	 *
	 * @generated from protobuf enum value: PH = 608;
	 */
	PH = 608,
	/**
	 * Pitcairn
	 *
	 * @generated from protobuf enum value: PN = 612;
	 */
	PN = 612,
	/**
	 * Poland
	 *
	 * @generated from protobuf enum value: PL = 616;
	 */
	PL = 616,
	/**
	 * Portugal
	 *
	 * @generated from protobuf enum value: PT = 620;
	 */
	PT = 620,
	/**
	 * Puerto Rico
	 *
	 * @generated from protobuf enum value: PR = 630;
	 */
	PR = 630,
	/**
	 * Qatar
	 *
	 * @generated from protobuf enum value: QA = 634;
	 */
	QA = 634,
	/**
	 * Réunion
	 *
	 * @generated from protobuf enum value: RE = 638;
	 */
	RE = 638,
	/**
	 * Romania
	 *
	 * @generated from protobuf enum value: RO = 642;
	 */
	RO = 642,
	/**
	 * Russian Federation
	 *
	 * @generated from protobuf enum value: RU = 643;
	 */
	RU = 643,
	/**
	 * Rwanda
	 *
	 * @generated from protobuf enum value: RW = 646;
	 */
	RW = 646,
	/**
	 * Saint Barthélemy
	 *
	 * @generated from protobuf enum value: BL = 652;
	 */
	BL = 652,
	/**
	 * "Saint Helena, Ascension and Tristan da Cunha"
	 *
	 * @generated from protobuf enum value: SH = 654;
	 */
	SH = 654,
	/**
	 * Saint Kitts and Nevis
	 *
	 * @generated from protobuf enum value: KN = 659;
	 */
	KN = 659,
	/**
	 * Saint Lucia
	 *
	 * @generated from protobuf enum value: LC = 662;
	 */
	LC = 662,
	/**
	 * Saint Martin (French part)
	 *
	 * @generated from protobuf enum value: MF = 663;
	 */
	MF = 663,
	/**
	 * Saint Pierre and Miquelon
	 *
	 * @generated from protobuf enum value: PM = 666;
	 */
	PM = 666,
	/**
	 * Saint Vincent and the Grenadines
	 *
	 * @generated from protobuf enum value: VC = 670;
	 */
	VC = 670,
	/**
	 * Samoa
	 *
	 * @generated from protobuf enum value: WS = 882;
	 */
	WS = 882,
	/**
	 * San Marino
	 *
	 * @generated from protobuf enum value: SM = 674;
	 */
	SM = 674,
	/**
	 * Sao Tome and Principe
	 *
	 * @generated from protobuf enum value: ST = 678;
	 */
	ST = 678,
	/**
	 * Saudi Arabia
	 *
	 * @generated from protobuf enum value: SA = 682;
	 */
	SA = 682,
	/**
	 * Senegal
	 *
	 * @generated from protobuf enum value: SN = 686;
	 */
	SN = 686,
	/**
	 * Serbia
	 *
	 * @generated from protobuf enum value: RS = 688;
	 */
	RS = 688,
	/**
	 * Seychelles
	 *
	 * @generated from protobuf enum value: SC = 690;
	 */
	SC = 690,
	/**
	 * Sierra Leone
	 *
	 * @generated from protobuf enum value: SL = 694;
	 */
	SL = 694,
	/**
	 * Singapore
	 *
	 * @generated from protobuf enum value: SG = 702;
	 */
	SG = 702,
	/**
	 * Sint Maarten (Dutch part)
	 *
	 * @generated from protobuf enum value: SX = 534;
	 */
	SX = 534,
	/**
	 * Slovakia
	 *
	 * @generated from protobuf enum value: SK = 703;
	 */
	SK = 703,
	/**
	 * Slovenia
	 *
	 * @generated from protobuf enum value: SI = 705;
	 */
	SI = 705,
	/**
	 * Solomon Islands
	 *
	 * @generated from protobuf enum value: SB = 90;
	 */
	SB = 90,
	/**
	 * Somalia
	 *
	 * @generated from protobuf enum value: SO = 706;
	 */
	SO = 706,
	/**
	 * South Africa
	 *
	 * @generated from protobuf enum value: ZA = 710;
	 */
	ZA = 710,
	/**
	 * South Georgia and the South Sandwich Islands
	 *
	 * @generated from protobuf enum value: GS = 239;
	 */
	GS = 239,
	/**
	 * South Sudan
	 *
	 * @generated from protobuf enum value: SS = 728;
	 */
	SS = 728,
	/**
	 * Spain
	 *
	 * @generated from protobuf enum value: ES = 724;
	 */
	ES = 724,
	/**
	 * Sri Lanka
	 *
	 * @generated from protobuf enum value: LK = 144;
	 */
	LK = 144,
	/**
	 * Sudan
	 *
	 * @generated from protobuf enum value: SD = 729;
	 */
	SD = 729,
	/**
	 * Suriname
	 *
	 * @generated from protobuf enum value: SR = 740;
	 */
	SR = 740,
	/**
	 * Svalbard and Jan Mayen
	 *
	 * @generated from protobuf enum value: SJ = 744;
	 */
	SJ = 744,
	/**
	 * Swaziland
	 *
	 * @generated from protobuf enum value: SZ = 748;
	 */
	SZ = 748,
	/**
	 * Sweden
	 *
	 * @generated from protobuf enum value: SE = 752;
	 */
	SE = 752,
	/**
	 * Switzerland
	 *
	 * @generated from protobuf enum value: CH = 756;
	 */
	CH = 756,
	/**
	 * Syrian Arab Republic
	 *
	 * @generated from protobuf enum value: SY = 760;
	 */
	SY = 760,
	/**
	 * "Taiwan, Province of China"
	 *
	 * @generated from protobuf enum value: TW = 158;
	 */
	TW = 158,
	/**
	 * Tajikistan
	 *
	 * @generated from protobuf enum value: TJ = 762;
	 */
	TJ = 762,
	/**
	 * "Tanzania, United Republic of"
	 *
	 * @generated from protobuf enum value: TZ = 834;
	 */
	TZ = 834,
	/**
	 * Thailand
	 *
	 * @generated from protobuf enum value: TH = 764;
	 */
	TH = 764,
	/**
	 * Timor-Leste
	 *
	 * @generated from protobuf enum value: TL = 626;
	 */
	TL = 626,
	/**
	 * Togo
	 *
	 * @generated from protobuf enum value: TG = 768;
	 */
	TG = 768,
	/**
	 * Tokelau
	 *
	 * @generated from protobuf enum value: TK = 772;
	 */
	TK = 772,
	/**
	 * Tonga
	 *
	 * @generated from protobuf enum value: TO = 776;
	 */
	TO = 776,
	/**
	 * Trinidad and Tobago
	 *
	 * @generated from protobuf enum value: TT = 780;
	 */
	TT = 780,
	/**
	 * Tunisia
	 *
	 * @generated from protobuf enum value: TN = 788;
	 */
	TN = 788,
	/**
	 * Turkey
	 *
	 * @generated from protobuf enum value: TR = 792;
	 */
	TR = 792,
	/**
	 * Turkmenistan
	 *
	 * @generated from protobuf enum value: TM = 795;
	 */
	TM = 795,
	/**
	 * Turks and Caicos Islands
	 *
	 * @generated from protobuf enum value: TC = 796;
	 */
	TC = 796,
	/**
	 * Tuvalu
	 *
	 * @generated from protobuf enum value: TV = 798;
	 */
	TV = 798,
	/**
	 * Uganda
	 *
	 * @generated from protobuf enum value: UG = 800;
	 */
	UG = 800,
	/**
	 * Ukraine
	 *
	 * @generated from protobuf enum value: UA = 804;
	 */
	UA = 804,
	/**
	 * United Arab Emirates
	 *
	 * @generated from protobuf enum value: AE = 784;
	 */
	AE = 784,
	/**
	 * United Kingdom
	 *
	 * @generated from protobuf enum value: GB = 826;
	 */
	GB = 826,
	/**
	 * United States
	 *
	 * @generated from protobuf enum value: US = 840;
	 */
	US = 840,
	/**
	 * United States Minor Outlying Islands
	 *
	 * @generated from protobuf enum value: UM = 581;
	 */
	UM = 581,
	/**
	 * Uruguay
	 *
	 * @generated from protobuf enum value: UY = 858;
	 */
	UY = 858,
	/**
	 * Uzbekistan
	 *
	 * @generated from protobuf enum value: UZ = 860;
	 */
	UZ = 860,
	/**
	 * Vanuatu
	 *
	 * @generated from protobuf enum value: VU = 548;
	 */
	VU = 548,
	/**
	 * "Venezuela, Bolivarian Republic of"
	 *
	 * @generated from protobuf enum value: VE = 862;
	 */
	VE = 862,
	/**
	 * "Viet Nam"
	 *
	 * @generated from protobuf enum value: VN = 704;
	 */
	VN = 704,
	/**
	 * "Virgin Islands, British"
	 *
	 * @generated from protobuf enum value: VG = 92;
	 */
	VG = 92,
	/**
	 * "Virgin Islands, U.S."
	 *
	 * @generated from protobuf enum value: VI = 850;
	 */
	VI = 850,
	/**
	 * Wallis and Futuna
	 *
	 * @generated from protobuf enum value: WF = 876;
	 */
	WF = 876,
	/**
	 * Western Sahara
	 *
	 * @generated from protobuf enum value: EH = 732;
	 */
	EH = 732,
	/**
	 * Yemen
	 *
	 * @generated from protobuf enum value: YE = 887;
	 */
	YE = 887,
	/**
	 * Zambia
	 *
	 * @generated from protobuf enum value: ZM = 894;
	 */
	ZM = 894,
	/**
	 * Zimbabwe
	 *
	 * @generated from protobuf enum value: ZW = 716;
	 */
	ZW = 716,
	/**
	 * Åland Islands
	 *
	 * @generated from protobuf enum value: AX = 248;
	 */
	AX = 248,
}
