// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/champion_select_request.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message tempest.lobby.ChampionSelectRequest
 */
export interface ChampionSelectRequest {
	/**
	 * @generated from protobuf field: string name = 1
	 */
	name: string; // to-do: add cosmetics
}
// @generated message type with reflection information, may provide speed optimized methods
class ChampionSelectRequest$Type extends MessageType<ChampionSelectRequest> {
	constructor() {
		super("tempest.lobby.ChampionSelectRequest", [
			{ no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<ChampionSelectRequest>): ChampionSelectRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.name = "";
		if (value !== undefined) {
			reflectionMergePartial<ChampionSelectRequest>(this, message, value);
		}
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: ChampionSelectRequest,
	): ChampionSelectRequest {
		let message = target ?? this.create(), end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string name */ 1:
					message.name = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw") {
						throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
					}
					let d = reader.skip(wireType);
					if (u !== false) {
						(u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
					}
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: ChampionSelectRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string name = 1; */
		if (message.name !== "") {
			writer.tag(1, WireType.LengthDelimited).string(message.name);
		}
		let u = options.writeUnknownFields;
		if (u !== false) {
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		}
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.ChampionSelectRequest
 */
export const ChampionSelectRequest = new ChampionSelectRequest$Type();
