// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/get_info_response.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import {
	MessageType,
	reflectionMergePartial,
	UnknownFieldHandler,
	WireType,
} from "@protobuf-ts/runtime";
import { AuthMethod } from "../common/auth_method";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message tempest.lobby.GetInfoResponse
 */
export interface GetInfoResponse {
	/**
	 * @generated from protobuf field: string name = 1
	 */
	name: string;
	/**
	 * @generated from protobuf field: string game = 2
	 */
	game: string;
	/**
	 * @generated from protobuf field: string version = 3
	 */
	version: string;
	/**
	 * @generated from protobuf field: uint32 players = 4
	 */
	players: number;
	/**
	 * @generated from protobuf field: uint32 max_players = 5
	 */
	maxPlayers: number;
	/**
	 * @generated from protobuf field: bool has_password = 6
	 */
	hasPassword: boolean;
	/**
	 * @generated from protobuf field: repeated tempest.common.AuthMethod auth_methods = 7
	 */
	authMethods: AuthMethod[];
}
// @generated message type with reflection information, may provide speed optimized methods
class GetInfoResponse$Type extends MessageType<GetInfoResponse> {
	constructor() {
		super("tempest.lobby.GetInfoResponse", [
			{ no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 2, name: "game", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 3, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 4, name: "players", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
			{ no: 5, name: "max_players", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
			{ no: 6, name: "has_password", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
			{
				no: 7,
				name: "auth_methods",
				kind: "enum",
				repeat: 1 /*RepeatType.PACKED*/,
				T: () => ["tempest.common.AuthMethod", AuthMethod, "AUTH_METHOD_"],
			},
		]);
	}
	create(value?: PartialMessage<GetInfoResponse>): GetInfoResponse {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.name = "";
		message.game = "";
		message.version = "";
		message.players = 0;
		message.maxPlayers = 0;
		message.hasPassword = false;
		message.authMethods = [];
		if (value !== undefined) reflectionMergePartial<GetInfoResponse>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: GetInfoResponse,
	): GetInfoResponse {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string name */ 1:
					message.name = reader.string();
					break;
				case /* string game */ 2:
					message.game = reader.string();
					break;
				case /* string version */ 3:
					message.version = reader.string();
					break;
				case /* uint32 players */ 4:
					message.players = reader.uint32();
					break;
				case /* uint32 max_players */ 5:
					message.maxPlayers = reader.uint32();
					break;
				case /* bool has_password */ 6:
					message.hasPassword = reader.bool();
					break;
				case /* repeated tempest.common.AuthMethod auth_methods */ 7:
					if (wireType === WireType.LengthDelimited)
						for (let e = reader.int32() + reader.pos; reader.pos < e; )
							message.authMethods.push(reader.int32());
					else message.authMethods.push(reader.int32());
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: GetInfoResponse,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string name = 1; */
		if (message.name !== "") writer.tag(1, WireType.LengthDelimited).string(message.name);
		/* string game = 2; */
		if (message.game !== "") writer.tag(2, WireType.LengthDelimited).string(message.game);
		/* string version = 3; */
		if (message.version !== "") writer.tag(3, WireType.LengthDelimited).string(message.version);
		/* uint32 players = 4; */
		if (message.players !== 0) writer.tag(4, WireType.Varint).uint32(message.players);
		/* uint32 max_players = 5; */
		if (message.maxPlayers !== 0) writer.tag(5, WireType.Varint).uint32(message.maxPlayers);
		/* bool has_password = 6; */
		if (message.hasPassword !== false) writer.tag(6, WireType.Varint).bool(message.hasPassword);
		/* repeated tempest.common.AuthMethod auth_methods = 7; */
		if (message.authMethods.length) {
			writer.tag(7, WireType.LengthDelimited).fork();
			for (let i = 0; i < message.authMethods.length; i++)
				writer.int32(message.authMethods[i]);
			writer.join();
		}
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.GetInfoResponse
 */
export const GetInfoResponse = new GetInfoResponse$Type();
