// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/join_lobby_success.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message tempest.lobby.JoinLobbySuccess
 */
export interface JoinLobbySuccess {
	/**
	 * @generated from protobuf field: string ticket = 1
	 */
	ticket: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class JoinLobbySuccess$Type extends MessageType<JoinLobbySuccess> {
	constructor() {
		super("tempest.lobby.JoinLobbySuccess", [
			{ no: 1, name: "ticket", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<JoinLobbySuccess>): JoinLobbySuccess {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.ticket = "";
		if (value !== undefined) reflectionMergePartial<JoinLobbySuccess>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: JoinLobbySuccess,
	): JoinLobbySuccess {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string ticket */ 1:
					message.ticket = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: JoinLobbySuccess,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string ticket = 1; */
		if (message.ticket !== "") writer.tag(1, WireType.LengthDelimited).string(message.ticket);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.JoinLobbySuccess
 */
export const JoinLobbySuccess = new JoinLobbySuccess$Type();
