// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/join_lobby_response.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { JoinLobbyError } from "./join_lobby_error";
import { JoinLobbySuccess } from "./join_lobby_success";
/**
 * @generated from protobuf message tempest.lobby.JoinLobbyResponse
 */
export interface JoinLobbyResponse {
	/**
	 * @generated from protobuf oneof: result
	 */
	result: {
		oneofKind: "success";
		/**
		 * @generated from protobuf field: tempest.lobby.JoinLobbySuccess success = 1
		 */
		success: JoinLobbySuccess;
	} | {
		oneofKind: "error";
		/**
		 * @generated from protobuf field: tempest.lobby.JoinLobbyError error = 2
		 */
		error: JoinLobbyError;
	} | {
		oneofKind: undefined;
	};
}
// @generated message type with reflection information, may provide speed optimized methods
class JoinLobbyResponse$Type extends MessageType<JoinLobbyResponse> {
	constructor() {
		super("tempest.lobby.JoinLobbyResponse", [
			{ no: 1, name: "success", kind: "message", oneof: "result", T: () => JoinLobbySuccess },
			{ no: 2, name: "error", kind: "message", oneof: "result", T: () => JoinLobbyError },
		]);
	}
	create(value?: PartialMessage<JoinLobbyResponse>): JoinLobbyResponse {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.result = { oneofKind: undefined };
		if (value !== undefined) {
			reflectionMergePartial<JoinLobbyResponse>(this, message, value);
		}
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: JoinLobbyResponse,
	): JoinLobbyResponse {
		let message = target ?? this.create(), end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* tempest.lobby.JoinLobbySuccess success */ 1:
					message.result = {
						oneofKind: "success",
						success: JoinLobbySuccess.internalBinaryRead(
							reader,
							reader.uint32(),
							options,
							(message.result as any).success,
						),
					};
					break;
				case /* tempest.lobby.JoinLobbyError error */ 2:
					message.result = {
						oneofKind: "error",
						error: JoinLobbyError.internalBinaryRead(reader, reader.uint32(), options, (message.result as any).error),
					};
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw") {
						throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
					}
					let d = reader.skip(wireType);
					if (u !== false) {
						(u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
					}
			}
		}
		return message;
	}
	internalBinaryWrite(message: JoinLobbyResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
		/* tempest.lobby.JoinLobbySuccess success = 1; */
		if (message.result.oneofKind === "success") {
			JoinLobbySuccess.internalBinaryWrite(
				message.result.success,
				writer.tag(1, WireType.LengthDelimited).fork(),
				options,
			).join();
		}
		/* tempest.lobby.JoinLobbyError error = 2; */
		if (message.result.oneofKind === "error") {
			JoinLobbyError.internalBinaryWrite(message.result.error, writer.tag(2, WireType.LengthDelimited).fork(), options)
				.join();
		}
		let u = options.writeUnknownFields;
		if (u !== false) {
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		}
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.JoinLobbyResponse
 */
export const JoinLobbyResponse = new JoinLobbyResponse$Type();
