// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/join_lobby_request.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import {
	MessageType,
	reflectionMergePartial,
	UnknownFieldHandler,
	WireType,
} from "@protobuf-ts/runtime";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message tempest.lobby.JoinLobbyRequest
 */
export interface JoinLobbyRequest {
	/**
	 * @generated from protobuf field: tempest.lobby.AuthMethod auth_method = 1
	 */
	authMethod: AuthMethod;
	/**
	 * @generated from protobuf field: string auth_value = 2
	 */
	authValue: string;
	/**
	 * @generated from protobuf field: optional string password = 5
	 */
	password?: string;
}
/**
 * @generated from protobuf enum tempest.lobby.AuthMethod
 */
export enum AuthMethod {
	/**
	 * @generated from protobuf enum value: AUTH_METHOD_UNSPECIFIED = 0;
	 */
	UNSPECIFIED = 0,
	/**
	 * @generated from protobuf enum value: AUTH_METHOD_PLAIN = 1;
	 */
	PLAIN = 1,
	/**
	 * @generated from protobuf enum value: AUTH_METHOD_TICKET = 2;
	 */
	TICKET = 2,
}
// @generated message type with reflection information, may provide speed optimized methods
class JoinLobbyRequest$Type extends MessageType<JoinLobbyRequest> {
	constructor() {
		super("tempest.lobby.JoinLobbyRequest", [
			{
				no: 1,
				name: "auth_method",
				kind: "enum",
				T: () => ["tempest.lobby.AuthMethod", AuthMethod, "AUTH_METHOD_"],
			},
			{ no: 2, name: "auth_value", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 5, name: "password", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<JoinLobbyRequest>): JoinLobbyRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.authMethod = 0;
		message.authValue = "";
		if (value !== undefined) reflectionMergePartial<JoinLobbyRequest>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: JoinLobbyRequest,
	): JoinLobbyRequest {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* tempest.lobby.AuthMethod auth_method */ 1:
					message.authMethod = reader.int32();
					break;
				case /* string auth_value */ 2:
					message.authValue = reader.string();
					break;
				case /* optional string password */ 5:
					message.password = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: JoinLobbyRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* tempest.lobby.AuthMethod auth_method = 1; */
		if (message.authMethod !== 0) writer.tag(1, WireType.Varint).int32(message.authMethod);
		/* string auth_value = 2; */
		if (message.authValue !== "")
			writer.tag(2, WireType.LengthDelimited).string(message.authValue);
		/* optional string password = 5; */
		if (message.password !== undefined)
			writer.tag(5, WireType.LengthDelimited).string(message.password);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.JoinLobbyRequest
 */
export const JoinLobbyRequest = new JoinLobbyRequest$Type();
