// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/join_lobby_error.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { JoinLobbyErrorCode } from "./join_lobby_error_code";
/**
 * @generated from protobuf message tempest.lobby.JoinLobbyError
 */
export interface JoinLobbyError {
	/**
	 * @generated from protobuf field: tempest.lobby.JoinLobbyErrorCode code = 1
	 */
	code: JoinLobbyErrorCode;
	/**
	 * @generated from protobuf field: string message = 2
	 */
	message: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class JoinLobbyError$Type extends MessageType<JoinLobbyError> {
	constructor() {
		super("tempest.lobby.JoinLobbyError", [
			{
				no: 1,
				name: "code",
				kind: "enum",
				T: () => ["tempest.lobby.JoinLobbyErrorCode", JoinLobbyErrorCode],
			},
			{ no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<JoinLobbyError>): JoinLobbyError {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.code = 0;
		message.message = "";
		if (value !== undefined) reflectionMergePartial<JoinLobbyError>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: JoinLobbyError,
	): JoinLobbyError {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* tempest.lobby.JoinLobbyErrorCode code */ 1:
					message.code = reader.int32();
					break;
				case /* string message */ 2:
					message.message = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: JoinLobbyError,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* tempest.lobby.JoinLobbyErrorCode code = 1; */
		if (message.code !== 0) writer.tag(1, WireType.Varint).int32(message.code);
		/* string message = 2; */
		if (message.message !== "") writer.tag(2, WireType.LengthDelimited).string(message.message);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.JoinLobbyError
 */
export const JoinLobbyError = new JoinLobbyError$Type();
