// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/join_lobby_error_code.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum tempest.lobby.JoinLobbyErrorCode
 */
export enum JoinLobbyErrorCode {
	/**
	 * @generated from protobuf enum value: JOIN_LOBBY_ERROR_CODE_UNSPECIFIED = 0;
	 */
	JOIN_LOBBY_ERROR_CODE_UNSPECIFIED = 0,
	/**
	 * @generated from protobuf enum value: INVALID_PASSWORD = 1;
	 */
	INVALID_PASSWORD = 1,
	/**
	 * @generated from protobuf enum value: LOBBY_FULL = 2;
	 */
	LOBBY_FULL = 2,
	/**
	 * @generated from protobuf enum value: LOBBY_INVALID = 3;
	 */
	LOBBY_INVALID = 3,
	/**
	 * @generated from protobuf enum value: BANNED = 4;
	 */
	BANNED = 4,
}
