// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/lobby_state_in_game.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import {
	MessageType,
	reflectionMergePartial,
	UnknownFieldHandler,
	WireType,
} from "@protobuf-ts/runtime";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message tempest.lobby.LobbyStateInGame
 */
export interface LobbyStateInGame {
	/**
	 * @generated from protobuf field: bool game_server_open = 1
	 */
	gameServerOpen: boolean;
	/**
	 * @generated from protobuf field: bool game_server_error = 2
	 */
	gameServerError: boolean;
	/**
	 * @generated from protobuf field: bool game_server_finished_running = 3
	 */
	gameServerFinishedRunning: boolean;
	/**
	 * @generated from protobuf field: string map_id = 4
	 */
	mapId: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class LobbyStateInGame$Type extends MessageType<LobbyStateInGame> {
	constructor() {
		super("tempest.lobby.LobbyStateInGame", [
			{ no: 1, name: "game_server_open", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
			{ no: 2, name: "game_server_error", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
			{
				no: 3,
				name: "game_server_finished_running",
				kind: "scalar",
				T: 8 /*ScalarType.BOOL*/,
			},
			{ no: 4, name: "map_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<LobbyStateInGame>): LobbyStateInGame {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.gameServerOpen = false;
		message.gameServerError = false;
		message.gameServerFinishedRunning = false;
		message.mapId = "";
		if (value !== undefined) reflectionMergePartial<LobbyStateInGame>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: LobbyStateInGame,
	): LobbyStateInGame {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* bool game_server_open */ 1:
					message.gameServerOpen = reader.bool();
					break;
				case /* bool game_server_error */ 2:
					message.gameServerError = reader.bool();
					break;
				case /* bool game_server_finished_running */ 3:
					message.gameServerFinishedRunning = reader.bool();
					break;
				case /* string map_id */ 4:
					message.mapId = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: LobbyStateInGame,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* bool game_server_open = 1; */
		if (message.gameServerOpen !== false)
			writer.tag(1, WireType.Varint).bool(message.gameServerOpen);
		/* bool game_server_error = 2; */
		if (message.gameServerError !== false)
			writer.tag(2, WireType.Varint).bool(message.gameServerError);
		/* bool game_server_finished_running = 3; */
		if (message.gameServerFinishedRunning !== false)
			writer.tag(3, WireType.Varint).bool(message.gameServerFinishedRunning);
		/* string map_id = 4; */
		if (message.mapId !== "") writer.tag(4, WireType.LengthDelimited).string(message.mapId);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.LobbyStateInGame
 */
export const LobbyStateInGame = new LobbyStateInGame$Type();
