// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/lobby_event_countdown.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message tempest.lobby.LobbyEventCountdown
 */
export interface LobbyEventCountdown {
	/**
	 * @generated from protobuf field: uint32 seconds = 1
	 */
	seconds: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class LobbyEventCountdown$Type extends MessageType<LobbyEventCountdown> {
	constructor() {
		super("tempest.lobby.LobbyEventCountdown", [
			{ no: 1, name: "seconds", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
		]);
	}
	create(value?: PartialMessage<LobbyEventCountdown>): LobbyEventCountdown {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.seconds = 0;
		if (value !== undefined) reflectionMergePartial<LobbyEventCountdown>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: LobbyEventCountdown,
	): LobbyEventCountdown {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* uint32 seconds */ 1:
					message.seconds = reader.uint32();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: LobbyEventCountdown,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* uint32 seconds = 1; */
		if (message.seconds !== 0) writer.tag(1, WireType.Varint).uint32(message.seconds);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.LobbyEventCountdown
 */
export const LobbyEventCountdown = new LobbyEventCountdown$Type();
