// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/lobby_state_waiting.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import {
	MessageType,
	reflectionMergePartial,
	UnknownFieldHandler,
	WireType,
} from "@protobuf-ts/runtime";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message tempest.lobby.LobbyStateWaiting
 */
export interface LobbyStateWaiting {
	/**
	 * @generated from protobuf field: uint32 minPlayers = 1
	 */
	minPlayers: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class LobbyStateWaiting$Type extends MessageType<LobbyStateWaiting> {
	constructor() {
		super("tempest.lobby.LobbyStateWaiting", [
			{ no: 1, name: "minPlayers", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
		]);
	}
	create(value?: PartialMessage<LobbyStateWaiting>): LobbyStateWaiting {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.minPlayers = 0;
		if (value !== undefined) reflectionMergePartial<LobbyStateWaiting>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: LobbyStateWaiting,
	): LobbyStateWaiting {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* uint32 minPlayers */ 1:
					message.minPlayers = reader.uint32();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: LobbyStateWaiting,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* uint32 minPlayers = 1; */
		if (message.minPlayers !== 0) writer.tag(1, WireType.Varint).uint32(message.minPlayers);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.LobbyStateWaiting
 */
export const LobbyStateWaiting = new LobbyStateWaiting$Type();
