// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/lobby_event_countdown.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import {
	MessageType,
	reflectionMergePartial,
	UnknownFieldHandler,
	WireType,
} from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message tempest.lobby.LobbyEventCountdown
 */
export interface LobbyEventCountdown {
	/**
	 * @generated from protobuf field: google.protobuf.Timestamp start_time = 1
	 */
	startTime?: Timestamp;
	/**
	 * @generated from protobuf field: uint32 seconds = 2
	 */
	seconds: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class LobbyEventCountdown$Type extends MessageType<LobbyEventCountdown> {
	constructor() {
		super("tempest.lobby.LobbyEventCountdown", [
			{ no: 1, name: "start_time", kind: "message", T: () => Timestamp },
			{ no: 2, name: "seconds", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
		]);
	}
	create(value?: PartialMessage<LobbyEventCountdown>): LobbyEventCountdown {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.seconds = 0;
		if (value !== undefined) reflectionMergePartial<LobbyEventCountdown>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: LobbyEventCountdown,
	): LobbyEventCountdown {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* google.protobuf.Timestamp start_time */ 1:
					message.startTime = Timestamp.internalBinaryRead(
						reader,
						reader.uint32(),
						options,
						message.startTime,
					);
					break;
				case /* uint32 seconds */ 2:
					message.seconds = reader.uint32();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: LobbyEventCountdown,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* google.protobuf.Timestamp start_time = 1; */
		if (message.startTime)
			Timestamp.internalBinaryWrite(
				message.startTime,
				writer.tag(1, WireType.LengthDelimited).fork(),
				options,
			).join();
		/* uint32 seconds = 2; */
		if (message.seconds !== 0) writer.tag(2, WireType.Varint).uint32(message.seconds);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.LobbyEventCountdown
 */
export const LobbyEventCountdown = new LobbyEventCountdown$Type();
