// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/lobby_event_player_join.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { LobbyPlayer } from "./lobby_player";
/**
 * @generated from protobuf message tempest.lobby.LobbyEventPlayerJoin
 */
export interface LobbyEventPlayerJoin {
	/**
	 * @generated from protobuf field: tempest.lobby.LobbyPlayer player = 1
	 */
	player?: LobbyPlayer;
}
// @generated message type with reflection information, may provide speed optimized methods
class LobbyEventPlayerJoin$Type extends MessageType<LobbyEventPlayerJoin> {
	constructor() {
		super("tempest.lobby.LobbyEventPlayerJoin", [
			{ no: 1, name: "player", kind: "message", T: () => LobbyPlayer },
		]);
	}
	create(value?: PartialMessage<LobbyEventPlayerJoin>): LobbyEventPlayerJoin {
		const message = globalThis.Object.create(this.messagePrototype!);
		if (value !== undefined) reflectionMergePartial<LobbyEventPlayerJoin>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: LobbyEventPlayerJoin,
	): LobbyEventPlayerJoin {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* tempest.lobby.LobbyPlayer player */ 1:
					message.player = LobbyPlayer.internalBinaryRead(
						reader,
						reader.uint32(),
						options,
						message.player,
					);
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: LobbyEventPlayerJoin,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* tempest.lobby.LobbyPlayer player = 1; */
		if (message.player)
			LobbyPlayer.internalBinaryWrite(
				message.player,
				writer.tag(1, WireType.LengthDelimited).fork(),
				options,
			).join();
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.LobbyEventPlayerJoin
 */
export const LobbyEventPlayerJoin = new LobbyEventPlayerJoin$Type();
