import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/lobby_event_player_kicked.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message tempest.lobby.LobbyEventPlayerKicked
 */
export interface LobbyEventPlayerKicked {
	/**
	 * @generated from protobuf field: string player_id = 1
	 */
	playerId: string;
	/**
	 * @generated from protobuf field: string reason = 2
	 */
	reason: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class LobbyEventPlayerKicked$Type extends MessageType<LobbyEventPlayerKicked> {
	constructor() {
		super("tempest.lobby.LobbyEventPlayerKicked", [
			{ no: 1, name: "player_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 2, name: "reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<LobbyEventPlayerKicked>): LobbyEventPlayerKicked {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.playerId = "";
		message.reason = "";
		if (value !== undefined)
			reflectionMergePartial<LobbyEventPlayerKicked>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: LobbyEventPlayerKicked,
	): LobbyEventPlayerKicked {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string player_id */ 1:
					message.playerId = reader.string();
					break;
				case /* string reason */ 2:
					message.reason = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: LobbyEventPlayerKicked,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string player_id = 1; */
		if (message.playerId !== "")
			writer.tag(1, WireType.LengthDelimited).string(message.playerId);
		/* string reason = 2; */
		if (message.reason !== "") writer.tag(2, WireType.LengthDelimited).string(message.reason);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.LobbyEventPlayerKicked
 */
export const LobbyEventPlayerKicked = new LobbyEventPlayerKicked$Type();
