// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/lobby_event_chat_message.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { LobbyChatMessage } from "./lobby_chat_message";
/**
 * @generated from protobuf message tempest.lobby.LobbyEventChatMessage
 */
export interface LobbyEventChatMessage {
	/**
	 * @generated from protobuf field: tempest.lobby.LobbyChatMessage chat_message = 1
	 */
	chatMessage?: LobbyChatMessage;
}
// @generated message type with reflection information, may provide speed optimized methods
class LobbyEventChatMessage$Type extends MessageType<LobbyEventChatMessage> {
	constructor() {
		super("tempest.lobby.LobbyEventChatMessage", [
			{ no: 1, name: "chat_message", kind: "message", T: () => LobbyChatMessage },
		]);
	}
	create(value?: PartialMessage<LobbyEventChatMessage>): LobbyEventChatMessage {
		const message = globalThis.Object.create(this.messagePrototype!);
		if (value !== undefined)
			reflectionMergePartial<LobbyEventChatMessage>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: LobbyEventChatMessage,
	): LobbyEventChatMessage {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* tempest.lobby.LobbyChatMessage chat_message */ 1:
					message.chatMessage = LobbyChatMessage.internalBinaryRead(
						reader,
						reader.uint32(),
						options,
						message.chatMessage,
					);
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: LobbyEventChatMessage,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* tempest.lobby.LobbyChatMessage chat_message = 1; */
		if (message.chatMessage)
			LobbyChatMessage.internalBinaryWrite(
				message.chatMessage,
				writer.tag(1, WireType.LengthDelimited).fork(),
				options,
			).join();
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.LobbyEventChatMessage
 */
export const LobbyEventChatMessage = new LobbyEventChatMessage$Type();
