// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/lobby_chat_message.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message tempest.lobby.LobbyChatMessage
 */
export interface LobbyChatMessage {
	/**
	 * @generated from protobuf field: string content = 1
	 */
	content: string;
	/**
	 * @generated from protobuf field: string author_id = 2
	 */
	authorId: string;
	/**
	 * @generated from protobuf field: google.protobuf.Timestamp sent_at = 3
	 */
	sentAt?: Timestamp;
}
// @generated message type with reflection information, may provide speed optimized methods
class LobbyChatMessage$Type extends MessageType<LobbyChatMessage> {
	constructor() {
		super("tempest.lobby.LobbyChatMessage", [
			{ no: 1, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 2, name: "author_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 3, name: "sent_at", kind: "message", T: () => Timestamp },
		]);
	}
	create(value?: PartialMessage<LobbyChatMessage>): LobbyChatMessage {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.content = "";
		message.authorId = "";
		if (value !== undefined) reflectionMergePartial<LobbyChatMessage>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: LobbyChatMessage,
	): LobbyChatMessage {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string content */ 1:
					message.content = reader.string();
					break;
				case /* string author_id */ 2:
					message.authorId = reader.string();
					break;
				case /* google.protobuf.Timestamp sent_at */ 3:
					message.sentAt = Timestamp.internalBinaryRead(
						reader,
						reader.uint32(),
						options,
						message.sentAt,
					);
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: LobbyChatMessage,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string content = 1; */
		if (message.content !== "") writer.tag(1, WireType.LengthDelimited).string(message.content);
		/* string author_id = 2; */
		if (message.authorId !== "")
			writer.tag(2, WireType.LengthDelimited).string(message.authorId);
		/* google.protobuf.Timestamp sent_at = 3; */
		if (message.sentAt)
			Timestamp.internalBinaryWrite(
				message.sentAt,
				writer.tag(3, WireType.LengthDelimited).fork(),
				options,
			).join();
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.LobbyChatMessage
 */
export const LobbyChatMessage = new LobbyChatMessage$Type();
