// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/lobby_state_map_vote.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message tempest.lobby.LobbyStateMapVote
 */
export interface LobbyStateMapVote {
}
// @generated message type with reflection information, may provide speed optimized methods
class LobbyStateMapVote$Type extends MessageType<LobbyStateMapVote> {
	constructor() {
		super("tempest.lobby.LobbyStateMapVote", []);
	}
	create(value?: PartialMessage<LobbyStateMapVote>): LobbyStateMapVote {
		const message = globalThis.Object.create(this.messagePrototype!);
		if (value !== undefined) {
			reflectionMergePartial<LobbyStateMapVote>(this, message, value);
		}
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: LobbyStateMapVote,
	): LobbyStateMapVote {
		let message = target ?? this.create(), end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				default:
					let u = options.readUnknownField;
					if (u === "throw") {
						throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
					}
					let d = reader.skip(wireType);
					if (u !== false) {
						(u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
					}
			}
		}
		return message;
	}
	internalBinaryWrite(message: LobbyStateMapVote, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
		let u = options.writeUnknownFields;
		if (u !== false) {
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		}
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.LobbyStateMapVote
 */
export const LobbyStateMapVote = new LobbyStateMapVote$Type();
