// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/map_vote_request.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import {
	MessageType,
	reflectionMergePartial,
	UnknownFieldHandler,
	WireType,
} from "@protobuf-ts/runtime";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message tempest.lobby.MapVoteRequest
 */
export interface MapVoteRequest {
	/**
	 * @generated from protobuf field: string mapId = 1
	 */
	mapId: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class MapVoteRequest$Type extends MessageType<MapVoteRequest> {
	constructor() {
		super("tempest.lobby.MapVoteRequest", [
			{ no: 1, name: "mapId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<MapVoteRequest>): MapVoteRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.mapId = "";
		if (value !== undefined) reflectionMergePartial<MapVoteRequest>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: MapVoteRequest,
	): MapVoteRequest {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string mapId */ 1:
					message.mapId = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: MapVoteRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string mapId = 1; */
		if (message.mapId !== "") writer.tag(1, WireType.LengthDelimited).string(message.mapId);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.MapVoteRequest
 */
export const MapVoteRequest = new MapVoteRequest$Type();
