// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/receive_lobby_events_request.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import {
	MessageType,
	reflectionMergePartial,
	UnknownFieldHandler,
	WireType,
} from "@protobuf-ts/runtime";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message tempest.lobby.ReceiveLobbyEventsRequest
 */
export interface ReceiveLobbyEventsRequest {
	/**
	 * @generated from protobuf field: string player_id = 1
	 */
	playerId: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class ReceiveLobbyEventsRequest$Type extends MessageType<ReceiveLobbyEventsRequest> {
	constructor() {
		super("tempest.lobby.ReceiveLobbyEventsRequest", [
			{ no: 1, name: "player_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<ReceiveLobbyEventsRequest>): ReceiveLobbyEventsRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.playerId = "";
		if (value !== undefined)
			reflectionMergePartial<ReceiveLobbyEventsRequest>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: ReceiveLobbyEventsRequest,
	): ReceiveLobbyEventsRequest {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string player_id */ 1:
					message.playerId = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: ReceiveLobbyEventsRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string player_id = 1; */
		if (message.playerId !== "")
			writer.tag(1, WireType.LengthDelimited).string(message.playerId);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.ReceiveLobbyEventsRequest
 */
export const ReceiveLobbyEventsRequest = new ReceiveLobbyEventsRequest$Type();
