import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { SendCommandError } from "./send_command_error";
import { SendCommandSuccess } from "./send_command_success";
// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/send_command_response.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message tempest.lobby.SendCommandResponse
 */
export interface SendCommandResponse {
	/**
	 * @generated from protobuf oneof: result
	 */
	result:
		| {
				oneofKind: "success";
				/**
				 * @generated from protobuf field: tempest.lobby.SendCommandSuccess success = 1
				 */
				success: SendCommandSuccess;
		  }
		| {
				oneofKind: "error";
				/**
				 * @generated from protobuf field: tempest.lobby.SendCommandError error = 2
				 */
				error: SendCommandError;
		  }
		| {
				oneofKind: undefined;
		  };
}
// @generated message type with reflection information, may provide speed optimized methods
class SendCommandResponse$Type extends MessageType<SendCommandResponse> {
	constructor() {
		super("tempest.lobby.SendCommandResponse", [
			{
				no: 1,
				name: "success",
				kind: "message",
				oneof: "result",
				T: () => SendCommandSuccess,
			},
			{ no: 2, name: "error", kind: "message", oneof: "result", T: () => SendCommandError },
		]);
	}
	create(value?: PartialMessage<SendCommandResponse>): SendCommandResponse {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.result = { oneofKind: undefined };
		if (value !== undefined) reflectionMergePartial<SendCommandResponse>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: SendCommandResponse,
	): SendCommandResponse {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* tempest.lobby.SendCommandSuccess success */ 1:
					message.result = {
						oneofKind: "success",
						success: SendCommandSuccess.internalBinaryRead(
							reader,
							reader.uint32(),
							options,
							(message.result as any).success,
						),
					};
					break;
				case /* tempest.lobby.SendCommandError error */ 2:
					message.result = {
						oneofKind: "error",
						error: SendCommandError.internalBinaryRead(
							reader,
							reader.uint32(),
							options,
							(message.result as any).error,
						),
					};
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: SendCommandResponse,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* tempest.lobby.SendCommandSuccess success = 1; */
		if (message.result.oneofKind === "success")
			SendCommandSuccess.internalBinaryWrite(
				message.result.success,
				writer.tag(1, WireType.LengthDelimited).fork(),
				options,
			).join();
		/* tempest.lobby.SendCommandError error = 2; */
		if (message.result.oneofKind === "error")
			SendCommandError.internalBinaryWrite(
				message.result.error,
				writer.tag(2, WireType.LengthDelimited).fork(),
				options,
			).join();
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.SendCommandResponse
 */
export const SendCommandResponse = new SendCommandResponse$Type();
