import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/send_command_request.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message tempest.lobby.SendCommandRequest
 */
export interface SendCommandRequest {
	/**
	 * @generated from protobuf field: string command = 1
	 */
	command: string;
	/**
	 * @generated from protobuf field: string arguments = 2
	 */
	arguments: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class SendCommandRequest$Type extends MessageType<SendCommandRequest> {
	constructor() {
		super("tempest.lobby.SendCommandRequest", [
			{ no: 1, name: "command", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 2, name: "arguments", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<SendCommandRequest>): SendCommandRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.command = "";
		message.arguments = "";
		if (value !== undefined) reflectionMergePartial<SendCommandRequest>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: SendCommandRequest,
	): SendCommandRequest {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string command */ 1:
					message.command = reader.string();
					break;
				case /* string arguments */ 2:
					message.arguments = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: SendCommandRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string command = 1; */
		if (message.command !== "") writer.tag(1, WireType.LengthDelimited).string(message.command);
		/* string arguments = 2; */
		if (message.arguments !== "")
			writer.tag(2, WireType.LengthDelimited).string(message.arguments);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.SendCommandRequest
 */
export const SendCommandRequest = new SendCommandRequest$Type();
