// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/send_chat_message_error_code.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum tempest.lobby.SendChatMessageErrorCode
 */
export enum SendChatMessageErrorCode {
	/**
	 * @generated from protobuf enum value: SEND_CHAT_MESSAGE_ERROR_CODE_UNSPECIFIED = 0;
	 */
	SEND_CHAT_MESSAGE_ERROR_CODE_UNSPECIFIED = 0,
	/**
	 * @generated from protobuf enum value: EMPTY_MESSAGE = 1;
	 */
	EMPTY_MESSAGE = 1,
	/**
	 * @generated from protobuf enum value: RATE_LIMITED = 2;
	 */
	RATE_LIMITED = 2,
	/**
	 * @generated from protobuf enum value: INVALID_CHANNEL = 3;
	 */
	INVALID_CHANNEL = 3,
}
