// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/send_command_error_code.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum tempest.lobby.SendCommandErrorCode
 */
export enum SendCommandErrorCode {
	/**
	 * @generated from protobuf enum value: SEND_COMMAND_ERROR_CODE_UNSPECIFIED = 0;
	 */
	SEND_COMMAND_ERROR_CODE_UNSPECIFIED = 0,
	/**
	 * @generated from protobuf enum value: UNKNOWN_COMMAND = 1;
	 */
	UNKNOWN_COMMAND = 1,
	/**
	 * @generated from protobuf enum value: FORBIDDEN = 2;
	 */
	FORBIDDEN = 2,
	/**
	 * @generated from protobuf enum value: INVALID_ARGUMENTS = 3;
	 */
	INVALID_ARGUMENTS = 3,
}
