import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/set_ready_request.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message tempest.lobby.SetReadyRequest
 */
export interface SetReadyRequest {
	/**
	 * @generated from protobuf field: bool ready = 1
	 */
	ready: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class SetReadyRequest$Type extends MessageType<SetReadyRequest> {
	constructor() {
		super("tempest.lobby.SetReadyRequest", [
			{ no: 1, name: "ready", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
		]);
	}
	create(value?: PartialMessage<SetReadyRequest>): SetReadyRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.ready = false;
		if (value !== undefined) reflectionMergePartial<SetReadyRequest>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: SetReadyRequest,
	): SetReadyRequest {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* bool ready */ 1:
					message.ready = reader.bool();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: SetReadyRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* bool ready = 1; */
		if (message.ready !== false) writer.tag(1, WireType.Varint).bool(message.ready);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.SetReadyRequest
 */
export const SetReadyRequest = new SetReadyRequest$Type();
