import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "lobby/switch_team_request.proto" (package "tempest.lobby", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message tempest.lobby.SwitchTeamRequest
 */
export interface SwitchTeamRequest {
	/**
	 * Target team: 1 = left team, 2 = right team, 0 = spectator (neither team)
	 *
	 * @generated from protobuf field: int32 team = 1
	 */
	team: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class SwitchTeamRequest$Type extends MessageType<SwitchTeamRequest> {
	constructor() {
		super("tempest.lobby.SwitchTeamRequest", [
			{ no: 1, name: "team", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
		]);
	}
	create(value?: PartialMessage<SwitchTeamRequest>): SwitchTeamRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.team = 0;
		if (value !== undefined) reflectionMergePartial<SwitchTeamRequest>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: SwitchTeamRequest,
	): SwitchTeamRequest {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* int32 team */ 1:
					message.team = reader.int32();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: SwitchTeamRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* int32 team = 1; */
		if (message.team !== 0) writer.tag(1, WireType.Varint).int32(message.team);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.lobby.SwitchTeamRequest
 */
export const SwitchTeamRequest = new SwitchTeamRequest$Type();
