// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "server_list/create_lobby_success.proto" (package "tempest.server_list", syntax proto3)
// tslint:disable
import {
	MessageType,
	reflectionMergePartial,
	UnknownFieldHandler,
	WireType,
} from "@protobuf-ts/runtime";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message tempest.server_list.CreateLobbySuccess
 */
export interface CreateLobbySuccess {
	/**
	 * @generated from protobuf field: string id = 1
	 */
	id: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateLobbySuccess$Type extends MessageType<CreateLobbySuccess> {
	constructor() {
		super("tempest.server_list.CreateLobbySuccess", [
			{ no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<CreateLobbySuccess>): CreateLobbySuccess {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.id = "";
		if (value !== undefined) reflectionMergePartial<CreateLobbySuccess>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: CreateLobbySuccess,
	): CreateLobbySuccess {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string id */ 1:
					message.id = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: CreateLobbySuccess,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string id = 1; */
		if (message.id !== "") writer.tag(1, WireType.LengthDelimited).string(message.id);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.server_list.CreateLobbySuccess
 */
export const CreateLobbySuccess = new CreateLobbySuccess$Type();
