// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "server_list/create_lobby_error_code.proto" (package "tempest.server_list", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum tempest.server_list.CreateLobbyErrorCode
 */
export enum CreateLobbyErrorCode {
	/**
	 * @generated from protobuf enum value: CREATE_LOBBY_ERROR_CODE_UNSPECIFIED = 0;
	 */
	CREATE_LOBBY_ERROR_CODE_UNSPECIFIED = 0,
	/**
	 * @generated from protobuf enum value: LOBBY_ALREADY_EXISTS = 1;
	 */
	LOBBY_ALREADY_EXISTS = 1,
	/**
	 * @generated from protobuf enum value: KEY_NOT_ALLOWED = 2;
	 */
	KEY_NOT_ALLOWED = 2,
}
