// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "server_list/get_server_by_id_request.proto" (package "tempest.server_list", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message tempest.server_list.GetServerByIdRequest
 */
export interface GetServerByIdRequest {
	/**
	 * @generated from protobuf field: string id = 1
	 */
	id: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetServerByIdRequest$Type extends MessageType<GetServerByIdRequest> {
	constructor() {
		super("tempest.server_list.GetServerByIdRequest", [
			{ no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<GetServerByIdRequest>): GetServerByIdRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.id = "";
		if (value !== undefined) {
			reflectionMergePartial<GetServerByIdRequest>(this, message, value);
		}
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: GetServerByIdRequest,
	): GetServerByIdRequest {
		let message = target ?? this.create(), end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string id */ 1:
					message.id = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw") {
						throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
					}
					let d = reader.skip(wireType);
					if (u !== false) {
						(u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
					}
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: GetServerByIdRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string id = 1; */
		if (message.id !== "") {
			writer.tag(1, WireType.LengthDelimited).string(message.id);
		}
		let u = options.writeUnknownFields;
		if (u !== false) {
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		}
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.server_list.GetServerByIdRequest
 */
export const GetServerByIdRequest = new GetServerByIdRequest$Type();
