// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "server_list/get_server_by_id_response.proto" (package "tempest.server_list", syntax proto3)
// tslint:disable
import {
	MessageType,
	reflectionMergePartial,
	UnknownFieldHandler,
	WireType,
} from "@protobuf-ts/runtime";
import { GetServerByIdError } from "./get_server_by_id_error";
import { ServerListing } from "./server_listing";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message tempest.server_list.GetServerByIdResponse
 */
export interface GetServerByIdResponse {
	/**
	 * @generated from protobuf oneof: result
	 */
	result:
		| {
				oneofKind: "success";
				/**
				 * @generated from protobuf field: tempest.server_list.ServerListing success = 1
				 */
				success: ServerListing;
		  }
		| {
				oneofKind: "error";
				/**
				 * @generated from protobuf field: tempest.server_list.GetServerByIdError error = 2
				 */
				error: GetServerByIdError;
		  }
		| {
				oneofKind: undefined;
		  };
}
// @generated message type with reflection information, may provide speed optimized methods
class GetServerByIdResponse$Type extends MessageType<GetServerByIdResponse> {
	constructor() {
		super("tempest.server_list.GetServerByIdResponse", [
			{ no: 1, name: "success", kind: "message", oneof: "result", T: () => ServerListing },
			{ no: 2, name: "error", kind: "message", oneof: "result", T: () => GetServerByIdError },
		]);
	}
	create(value?: PartialMessage<GetServerByIdResponse>): GetServerByIdResponse {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.result = { oneofKind: undefined };
		if (value !== undefined)
			reflectionMergePartial<GetServerByIdResponse>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: GetServerByIdResponse,
	): GetServerByIdResponse {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* tempest.server_list.ServerListing success */ 1:
					message.result = {
						oneofKind: "success",
						success: ServerListing.internalBinaryRead(
							reader,
							reader.uint32(),
							options,
							(message.result as any).success,
						),
					};
					break;
				case /* tempest.server_list.GetServerByIdError error */ 2:
					message.result = {
						oneofKind: "error",
						error: GetServerByIdError.internalBinaryRead(
							reader,
							reader.uint32(),
							options,
							(message.result as any).error,
						),
					};
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: GetServerByIdResponse,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* tempest.server_list.ServerListing success = 1; */
		if (message.result.oneofKind === "success")
			ServerListing.internalBinaryWrite(
				message.result.success,
				writer.tag(1, WireType.LengthDelimited).fork(),
				options,
			).join();
		/* tempest.server_list.GetServerByIdError error = 2; */
		if (message.result.oneofKind === "error")
			GetServerByIdError.internalBinaryWrite(
				message.result.error,
				writer.tag(2, WireType.LengthDelimited).fork(),
				options,
			).join();
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.server_list.GetServerByIdResponse
 */
export const GetServerByIdResponse = new GetServerByIdResponse$Type();
