// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "server_list/get_server_by_id_error_code.proto" (package "tempest.server_list", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum tempest.server_list.GetServerByIdErrorCode
 */
export enum GetServerByIdErrorCode {
	/**
	 * @generated from protobuf enum value: GET_SERVER_BY_ID_ERROR_CODE_UNSPECIFIED = 0;
	 */
	GET_SERVER_BY_ID_ERROR_CODE_UNSPECIFIED = 0,
	/**
	 * @generated from protobuf enum value: ID_NOT_FOUND = 1;
	 */
	ID_NOT_FOUND = 1,
}
