// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "server_list/get_server_by_id_error.proto" (package "tempest.server_list", syntax proto3)
// tslint:disable
import {
	MessageType,
	reflectionMergePartial,
	UnknownFieldHandler,
	WireType,
} from "@protobuf-ts/runtime";
import { GetServerByIdErrorCode } from "./get_server_by_id_error_code";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message tempest.server_list.GetServerByIdError
 */
export interface GetServerByIdError {
	/**
	 * @generated from protobuf field: tempest.server_list.GetServerByIdErrorCode code = 1
	 */
	code: GetServerByIdErrorCode;
	/**
	 * @generated from protobuf field: string message = 2
	 */
	message: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetServerByIdError$Type extends MessageType<GetServerByIdError> {
	constructor() {
		super("tempest.server_list.GetServerByIdError", [
			{
				no: 1,
				name: "code",
				kind: "enum",
				T: () => ["tempest.server_list.GetServerByIdErrorCode", GetServerByIdErrorCode],
			},
			{ no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<GetServerByIdError>): GetServerByIdError {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.code = 0;
		message.message = "";
		if (value !== undefined) reflectionMergePartial<GetServerByIdError>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: GetServerByIdError,
	): GetServerByIdError {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* tempest.server_list.GetServerByIdErrorCode code */ 1:
					message.code = reader.int32();
					break;
				case /* string message */ 2:
					message.message = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: GetServerByIdError,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* tempest.server_list.GetServerByIdErrorCode code = 1; */
		if (message.code !== 0) writer.tag(1, WireType.Varint).int32(message.code);
		/* string message = 2; */
		if (message.message !== "") writer.tag(2, WireType.LengthDelimited).string(message.message);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.server_list.GetServerByIdError
 */
export const GetServerByIdError = new GetServerByIdError$Type();
