// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "server_list/server_list_service.proto" (package "tempest.server_list", syntax proto3)
// tslint:disable
import { HeartbeatLobbyResponse } from "./heartbeat_lobby_response";
import { HeartbeatLobbyRequest } from "./heartbeat_lobby_request";
import { GetServerByIdRequest } from "./get_server_by_id_request";
import { ServerListing } from "./server_listing";
import { GetServersRequest } from "./get_servers_request";
import { CreateLobbyResponse } from "./create_lobby_response";
import { CreateLobbyRequest } from "./create_lobby_request";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service tempest.server_list.ServerList
 */
export const ServerList = new ServiceType("tempest.server_list.ServerList", [
	{ name: "CreateLobby", options: {}, I: CreateLobbyRequest, O: CreateLobbyResponse },
	{
		name: "GetServers",
		serverStreaming: true,
		options: {},
		I: GetServersRequest,
		O: ServerListing,
	},
	{ name: "GetServerById", options: {}, I: GetServerByIdRequest, O: ServerListing },
	{ name: "HeartbeatLobby", options: {}, I: HeartbeatLobbyRequest, O: HeartbeatLobbyResponse },
]);
