import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import { ServerList } from "./server_list_service";
import type { CreateLobbyRequest } from "./create_lobby_request";
import type { CreateLobbyResponse } from "./create_lobby_response";
import type { GetServerByIdRequest } from "./get_server_by_id_request";
import type { GetServerByIdResponse } from "./get_server_by_id_response";
import type { GetServersRequest } from "./get_servers_request";
import type { ServerListing } from "./server_listing";
import type { UpdateLobbyRequest } from "./update_lobby_request";
import type { UpdateLobbyResponse } from "./update_lobby_response";
// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "server_list/server_list_service.proto" (package "tempest.server_list", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service tempest.server_list.ServerList
 */
export interface IServerListClient {
	/**
	 * @generated from protobuf rpc: CreateLobby
	 */
	createLobby(
		input: CreateLobbyRequest,
		options?: RpcOptions,
	): UnaryCall<CreateLobbyRequest, CreateLobbyResponse>;
	/**
	 * @generated from protobuf rpc: UpdateLobby
	 */
	updateLobby(
		input: UpdateLobbyRequest,
		options?: RpcOptions,
	): UnaryCall<UpdateLobbyRequest, UpdateLobbyResponse>;
	/**
	 * @generated from protobuf rpc: GetServers
	 */
	getServers(
		input: GetServersRequest,
		options?: RpcOptions,
	): ServerStreamingCall<GetServersRequest, ServerListing>;
	/**
	 * @generated from protobuf rpc: GetServerById
	 */
	getServerById(
		input: GetServerByIdRequest,
		options?: RpcOptions,
	): UnaryCall<GetServerByIdRequest, GetServerByIdResponse>;
}
/**
 * @generated from protobuf service tempest.server_list.ServerList
 */
export class ServerListClient implements IServerListClient, ServiceInfo {
	typeName = ServerList.typeName;
	methods = ServerList.methods;
	options = ServerList.options;
	constructor(private readonly _transport: RpcTransport) {}
	/**
	 * @generated from protobuf rpc: CreateLobby
	 */
	createLobby(
		input: CreateLobbyRequest,
		options?: RpcOptions,
	): UnaryCall<CreateLobbyRequest, CreateLobbyResponse> {
		const method = this.methods[0],
			opt = this._transport.mergeOptions(options);
		return stackIntercept<CreateLobbyRequest, CreateLobbyResponse>(
			"unary",
			this._transport,
			method,
			opt,
			input,
		);
	}
	/**
	 * @generated from protobuf rpc: UpdateLobby
	 */
	updateLobby(
		input: UpdateLobbyRequest,
		options?: RpcOptions,
	): UnaryCall<UpdateLobbyRequest, UpdateLobbyResponse> {
		const method = this.methods[1],
			opt = this._transport.mergeOptions(options);
		return stackIntercept<UpdateLobbyRequest, UpdateLobbyResponse>(
			"unary",
			this._transport,
			method,
			opt,
			input,
		);
	}
	/**
	 * @generated from protobuf rpc: GetServers
	 */
	getServers(
		input: GetServersRequest,
		options?: RpcOptions,
	): ServerStreamingCall<GetServersRequest, ServerListing> {
		const method = this.methods[2],
			opt = this._transport.mergeOptions(options);
		return stackIntercept<GetServersRequest, ServerListing>(
			"serverStreaming",
			this._transport,
			method,
			opt,
			input,
		);
	}
	/**
	 * @generated from protobuf rpc: GetServerById
	 */
	getServerById(
		input: GetServerByIdRequest,
		options?: RpcOptions,
	): UnaryCall<GetServerByIdRequest, GetServerByIdResponse> {
		const method = this.methods[3],
			opt = this._transport.mergeOptions(options);
		return stackIntercept<GetServerByIdRequest, GetServerByIdResponse>(
			"unary",
			this._transport,
			method,
			opt,
			input,
		);
	}
}
