import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { CreateLobbyRequest } from "./create_lobby_request";
import { CreateLobbyResponse } from "./create_lobby_response";
import { GetServerByIdRequest } from "./get_server_by_id_request";
// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "server_list/server_list_service.proto" (package "tempest.server_list", syntax proto3)
// tslint:disable
import { GetServerByIdResponse } from "./get_server_by_id_response";
import { GetServersRequest } from "./get_servers_request";
import { ServerListing } from "./server_listing";
import { UpdateLobbyRequest } from "./update_lobby_request";
import { UpdateLobbyResponse } from "./update_lobby_response";
/**
 * @generated ServiceType for protobuf service tempest.server_list.ServerList
 */
export const ServerList = new ServiceType("tempest.server_list.ServerList", [
	{ name: "CreateLobby", options: {}, I: CreateLobbyRequest, O: CreateLobbyResponse },
	{ name: "UpdateLobby", options: {}, I: UpdateLobbyRequest, O: UpdateLobbyResponse },
	{
		name: "GetServers",
		serverStreaming: true,
		options: {},
		I: GetServersRequest,
		O: ServerListing,
	},
	{ name: "GetServerById", options: {}, I: GetServerByIdRequest, O: GetServerByIdResponse },
]);
