// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "server_list/update_lobby_success.proto" (package "tempest.server_list", syntax proto3)
// tslint:disable
import { MessageType, reflectionMergePartial, UnknownFieldHandler } from "@protobuf-ts/runtime";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message tempest.server_list.UpdateLobbySuccess
 */
export interface UpdateLobbySuccess {}
// @generated message type with reflection information, may provide speed optimized methods
class UpdateLobbySuccess$Type extends MessageType<UpdateLobbySuccess> {
	constructor() {
		super("tempest.server_list.UpdateLobbySuccess", []);
	}
	create(value?: PartialMessage<UpdateLobbySuccess>): UpdateLobbySuccess {
		const message = globalThis.Object.create(this.messagePrototype!);
		if (value !== undefined) reflectionMergePartial<UpdateLobbySuccess>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: UpdateLobbySuccess,
	): UpdateLobbySuccess {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: UpdateLobbySuccess,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.server_list.UpdateLobbySuccess
 */
export const UpdateLobbySuccess = new UpdateLobbySuccess$Type();
