// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "server_list/update_lobby_error.proto" (package "tempest.server_list", syntax proto3)
// tslint:disable
import {
	MessageType,
	reflectionMergePartial,
	UnknownFieldHandler,
	WireType,
} from "@protobuf-ts/runtime";
import { UpdateLobbyErrorCode } from "./update_lobby_error_code";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message tempest.server_list.UpdateLobbyError
 */
export interface UpdateLobbyError {
	/**
	 * @generated from protobuf field: tempest.server_list.UpdateLobbyErrorCode code = 1
	 */
	code: UpdateLobbyErrorCode;
}
// @generated message type with reflection information, may provide speed optimized methods
class UpdateLobbyError$Type extends MessageType<UpdateLobbyError> {
	constructor() {
		super("tempest.server_list.UpdateLobbyError", [
			{
				no: 1,
				name: "code",
				kind: "enum",
				T: () => ["tempest.server_list.UpdateLobbyErrorCode", UpdateLobbyErrorCode],
			},
		]);
	}
	create(value?: PartialMessage<UpdateLobbyError>): UpdateLobbyError {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.code = 0;
		if (value !== undefined) reflectionMergePartial<UpdateLobbyError>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: UpdateLobbyError,
	): UpdateLobbyError {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* tempest.server_list.UpdateLobbyErrorCode code */ 1:
					message.code = reader.int32();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: UpdateLobbyError,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* tempest.server_list.UpdateLobbyErrorCode code = 1; */
		if (message.code !== 0) writer.tag(1, WireType.Varint).int32(message.code);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.server_list.UpdateLobbyError
 */
export const UpdateLobbyError = new UpdateLobbyError$Type();
