// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "server_list/update_lobby_error_code.proto" (package "tempest.server_list", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum tempest.server_list.UpdateLobbyErrorCode
 */
export enum UpdateLobbyErrorCode {
	/**
	 * @generated from protobuf enum value: UPDATE_LOBBY_ERROR_CODE_UNSPECIFIED = 0;
	 */
	UPDATE_LOBBY_ERROR_CODE_UNSPECIFIED = 0,
	/**
	 * @generated from protobuf enum value: NOT_FOUND = 1;
	 */
	NOT_FOUND = 1,
}
