// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "server_list/update_lobby_request.proto" (package "tempest.server_list", syntax proto3)
// tslint:disable
import {
	MessageType,
	reflectionMergePartial,
	UnknownFieldHandler,
	WireType,
} from "@protobuf-ts/runtime";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message tempest.server_list.UpdateLobbyRequest
 */
export interface UpdateLobbyRequest {
	/**
	 * @generated from protobuf field: string id = 1
	 */
	id: string;
	/**
	 * @generated from protobuf field: optional uint32 players = 2
	 */
	players?: number;
	/**
	 * @generated from protobuf field: optional uint32 bots = 3
	 */
	bots?: number;
	/**
	 * @generated from protobuf field: optional uint32 spectators = 4
	 */
	spectators?: number;
	/**
	 * @generated from protobuf field: optional string map = 5
	 */
	map?: string;
	/**
	 * @generated from protobuf field: optional string map_id = 6
	 */
	mapId?: string;
	/**
	 * @generated from protobuf field: optional bool joinable = 7
	 */
	joinable?: boolean;
	/**
	 * @generated from protobuf field: optional bool join_in_progress = 8
	 */
	joinInProgress?: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class UpdateLobbyRequest$Type extends MessageType<UpdateLobbyRequest> {
	constructor() {
		super("tempest.server_list.UpdateLobbyRequest", [
			{ no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 2, name: "players", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
			{ no: 3, name: "bots", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
			{ no: 4, name: "spectators", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
			{ no: 5, name: "map", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
			{ no: 6, name: "map_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
			{ no: 7, name: "joinable", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
			{
				no: 8,
				name: "join_in_progress",
				kind: "scalar",
				opt: true,
				T: 8 /*ScalarType.BOOL*/,
			},
		]);
	}
	create(value?: PartialMessage<UpdateLobbyRequest>): UpdateLobbyRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.id = "";
		if (value !== undefined) reflectionMergePartial<UpdateLobbyRequest>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: UpdateLobbyRequest,
	): UpdateLobbyRequest {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string id */ 1:
					message.id = reader.string();
					break;
				case /* optional uint32 players */ 2:
					message.players = reader.uint32();
					break;
				case /* optional uint32 bots */ 3:
					message.bots = reader.uint32();
					break;
				case /* optional uint32 spectators */ 4:
					message.spectators = reader.uint32();
					break;
				case /* optional string map */ 5:
					message.map = reader.string();
					break;
				case /* optional string map_id */ 6:
					message.mapId = reader.string();
					break;
				case /* optional bool joinable */ 7:
					message.joinable = reader.bool();
					break;
				case /* optional bool join_in_progress */ 8:
					message.joinInProgress = reader.bool();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: UpdateLobbyRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string id = 1; */
		if (message.id !== "") writer.tag(1, WireType.LengthDelimited).string(message.id);
		/* optional uint32 players = 2; */
		if (message.players !== undefined) writer.tag(2, WireType.Varint).uint32(message.players);
		/* optional uint32 bots = 3; */
		if (message.bots !== undefined) writer.tag(3, WireType.Varint).uint32(message.bots);
		/* optional uint32 spectators = 4; */
		if (message.spectators !== undefined)
			writer.tag(4, WireType.Varint).uint32(message.spectators);
		/* optional string map = 5; */
		if (message.map !== undefined) writer.tag(5, WireType.LengthDelimited).string(message.map);
		/* optional string map_id = 6; */
		if (message.mapId !== undefined)
			writer.tag(6, WireType.LengthDelimited).string(message.mapId);
		/* optional bool joinable = 7; */
		if (message.joinable !== undefined) writer.tag(7, WireType.Varint).bool(message.joinable);
		/* optional bool join_in_progress = 8; */
		if (message.joinInProgress !== undefined)
			writer.tag(8, WireType.Varint).bool(message.joinInProgress);
		let u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message tempest.server_list.UpdateLobbyRequest
 */
export const UpdateLobbyRequest = new UpdateLobbyRequest$Type();
